=== anborr/LOIN-XML-Schema/src/xml/EN_ISO_23387.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
	
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" 
	xmlns="https://iso.org/2022/ProductDataTemplates"
	elementFormDefault="qualified"
	targetNamespace="https://iso.org/2022/ProductDataTemplates"
	
	
	xmlns:xlink="http://www.w3.org/1999/xlink"
	>
	
	
	<xs:import namespace="http://www.w3.org/1999/xlink" schemaLocation="http://www.w3.org/1999/xlink.xsd" />
	
	<xs:element name="DT_Library">
		<xs:annotation>
			<xs:documentation>To be exported as xtdDictionary in ISO 12006-3</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="T_DT_Library"/>
			</xs:complexContent>
		</xs:complexType>
		<xs:keyref name="RefDoc_Link" refer="Document_ID">
			<xs:selector xpath="ReferenceDocument"/>
			<xs:field xpath="@UUID"/>
		</xs:keyref>
		<xs:key name="Document_ID">
			<xs:selector xpath="*/ReferenceDocument"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:key>
		<xs:key name="Language_Code">
			<xs:selector xpath="Language"/>
			<xs:field xpath="@Code"/>
		</xs:key>
		<xs:keyref name="PredefValues_Lang_Link" refer="Language_Code">
			<xs:selector xpath="*/PredefinedValues"/>
			<xs:field xpath="@LanguageCode"/>
		</xs:keyref>
	<!--	<xs:keyref name="CO_Lang_Link" refer="Language_Code">
			<xs:selector xpath="*/Name | */Definition | *"/>
			<xs:field xpath="@LanguageCode"/>
		</xs:keyref>-->
		<xs:key name="CO_Key">
			<xs:selector xpath="ConstructionObject"/>
			<xs:field xpath="@UUID"/>
		</xs:key>
		<xs:unique name="Unique_UUID">
			<xs:selector xpath="*"/>
			<xs:field xpath="@UUID"/>
		</xs:unique>
		<xs:unique name="Unique_Name_UUID">
			<xs:selector xpath="*/Name"/>
			<xs:field xpath="@UUID"/>
		</xs:unique>
		<xs:unique name="Unique_Def_UUID">
			<xs:selector xpath="*/Definition"/>
			<xs:field xpath="@UUID"/>
		</xs:unique>
		<xs:keyref name="LINK_CO" refer="CO_Key">
			<xs:selector xpath="DataTemplate/IsDataTemplateFor"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:keyref>
		<xs:key name="Pset_Key">
			<xs:selector xpath="SetOfProperties"/>
			<xs:field xpath="@UUID"/>
		</xs:key>
		<xs:keyref name="LINK_SubPSet" refer="Pset_Key">
			<xs:selector xpath="*/SetOfProperties"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:keyref>
		<xs:key name="Property_Key">
			<xs:selector xpath="Property"/>
			<xs:field xpath="@UUID"/>
		</xs:key>
		<xs:keyref name="Link_Pset_Property" refer="Property_Key">
			<xs:selector xpath="*/Property"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:keyref>
		<xs:key name="Unit_Key">
			<xs:selector xpath="Unit"/>
			<xs:field xpath="@UUID"/>
		</xs:key>
		<xs:keyref name="Link_Unit" refer="Unit_Key">
			<xs:selector xpath="Property/Unit"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:keyref>
		<xs:key name="Dimension_Key">
			<xs:selector xpath="Dimension"/>
			<xs:field xpath="@UUID"/>
		</xs:key>
		<xs:keyref name="Link_Dimension" refer="Dimension_Key">
			<xs:selector xpath="*/Dimension"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:keyref>
		<xs:key name="PhysicalQuantity_Key">
			<xs:selector xpath="*/PhysicalQuantity"/>
			<xs:field xpath="@UUID"/>
		</xs:key>
		<xs:keyref name="Link_PhysicalQuantity" refer="PhysicalQuantity_Key">
			<xs:selector xpath="*/PhysicalQuantity"/>
			<xs:field xpath="@TargetUUID"/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="T_Boundary">
		<xs:attribute name="BoundaryLimit" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="MIN"/>
					<xs:enumeration value="MAX"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Inclusive" type="xs:boolean" use="required"/>
		<xs:attribute name="BoundaryValue" type="xs:double" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_ConstructionObject">
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="T_DataTemplate">
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component">
				<xs:sequence>
					<xs:element name="IsDataTemplateFor" type="T_Link">
						<xs:annotation>
							<xs:documentation>Link to the construction object described by the Data Template</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="SetOfProperties" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType mixed="false">
							<xs:complexContent>
								<xs:extension base="T_Link"/>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="T_Link"/>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="T_Dimension">
		<xs:attribute name="UUID" type="T_URI" use="required"/>
		<xs:attribute name="L" type="xs:int" use="required"/>
		<xs:attribute name="T" type="xs:int" use="required"/>
		<xs:attribute name="M" type="xs:int" use="required"/>
		<xs:attribute name="Theta" type="xs:int" use="required"/>
		<xs:attribute name="N" type="xs:int" use="required"/>
		<xs:attribute name="I" type="xs:int" use="required"/>
		<xs:attribute name="J" type="xs:int" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_DT_Library">
		<xs:sequence>
			<xs:element name="LibraryName" type="T_Text" maxOccurs="unbounded"/>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="ConstructionObject" type="T_ConstructionObject"
					maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>To be exported as xtdSubject in ISO 12006-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="DataTemplate" type="T_DataTemplate" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>To be exported as xtdSubject in ISO 12006-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="SetOfProperties" type="T_SetOfProperties" minOccurs="0"
					maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>To be exported as xtdSubject in ISO 12006-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Property" type="T_Property" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>To be exported as xtdProperty in ISO 12006-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Language" type="T_Language">
					<xs:annotation>
						<xs:documentation>To be exported as xtdLanguage in ISO 12006-3</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Unit" type="T_Unit" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="Dimension" type="T_Dimension" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element name="PhysicalQuantity" type="T_PhysicalQuantity" minOccurs="0"
					maxOccurs="unbounded"/>
				<xs:element name="ReferenceDocument" type="T_ReferenceDocument" minOccurs="0"
					maxOccurs="unbounded"/>
				<xs:element name="ExternalDictionary" type="T_ExternalDictionary" minOccurs="0"
					maxOccurs="unbounded"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="URI" type="T_URI" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_DT_Library_Component" abstract="true">
		<xs:sequence>
			<xs:element name="Name" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="T_Text"/>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Definition" type="T_Text" maxOccurs="unbounded"/>
			<xs:element name="ReferenceDocument" type="T_Link" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="ExternalDictionary" type="T_Link" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="URI" type="T_URI" use="required"/>
		<xs:attribute name="Date" type="xs:dateTime" use="required"/>
		<xs:attribute name="Document_URI" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="T_ExternalDictionary">
		<xs:attribute name="DictionaryName" type="xs:string" use="required"/>
		<xs:attribute name="URI" type="T_URI" use="optional"/>
	</xs:complexType>
	<xs:complexType name="T_Language">
		<xs:attribute name="URI" type="T_URI" use="required"/>
		<xs:attribute name="Code" type="xs:string" use="required"/>
		<xs:attribute name="Name" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_Link">
		<xs:attribute name="LinkURI" type="T_URI" use="optional">
			<xs:annotation>
				<xs:documentation>This is mandatory when wanting to export to IFD in order to ccreate xtdRelationshipToSubject between xtdSubjects</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute ref="xlink:title" use="required"/>
		<xs:attribute ref="xlink:href" use="required"/>
		
		<!---
			
			These should be refeferences to URIs using xlink:href
			
		<xs:attribute name="TargetUUID" type="T_URI" use="required"/>
		-->
		
	</xs:complexType>
	<xs:complexType name="T_PhysicalQuantity">
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component">
				<xs:sequence>
					<xs:element name="Dimension" type="T_Link"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="T_PredefinedValue">
		<xs:attribute name="OrderNo" type="xs:int" use="required"/>
		<xs:attribute name="Value" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="T_PredefinedValues">
		<xs:sequence>
			<xs:element name="Unit" type="T_Link" minOccurs="0"/>
			<xs:element name="Values">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ValueItem" type="T_PredefinedValue" maxOccurs="unbounded"
						/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="URI" type="T_URI" use="required"/>
		<xs:attribute name="LanguageCode" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="T_Property">
		<xs:annotation>
			<xs:documentation>xtdProperty in ISO 12006-3</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component">
				<xs:sequence>
					<xs:element name="Datatype" type="T_Datatype"/>
					<xs:element name="Symbol" type="xs:string" minOccurs="0"/>
					<xs:element name="Unit" type="T_Link" minOccurs="0" maxOccurs="unbounded"/>
					<xs:element name="PhysicalQuantity" type="T_Link" minOccurs="0"/>
					<xs:element name="PredefinedValues" type="T_PredefinedValues" minOccurs="0"
						maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>One set of predefined values per language or per Unit</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Boundary" type="T_Boundary" minOccurs="0"
						maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="T_ReferenceDocument">
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component">
				<xs:attribute name="DateOfPublication" type="xs:dateTime" use="optional"/>
				<xs:attribute name="Author" type="xs:string" use="optional"/>
				<xs:attribute name="ISBN" type="xs:string" use="optional"/>
				<xs:attribute name="Publisher" type="xs:string" use="optional"/>
				<xs:attribute ref="xlink:href" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="T_SetOfProperties">
		<xs:annotation>
			<xs:documentation>xtdSubject in ISO 12006-3</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component">
				<xs:sequence>
					<xs:element name="SetOfProperties" minOccurs="0" maxOccurs="unbounded">
						<xs:complexType mixed="false">
							<xs:complexContent>
								<xs:extension base="T_Link"/>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="Property" maxOccurs="unbounded">
						<xs:complexType>
							<xs:complexContent>
								<xs:extension base="T_Link"/>
							</xs:complexContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="T_Text">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="URI" type="T_URI" use="required"/>
				<xs:attribute name="LanguageCode" type="xs:string" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="T_Unit">
		<xs:complexContent>
			<xs:extension base="T_DT_Library_Component">
				<xs:sequence>
					<xs:element name="Dimension" type="T_Link"/>
				</xs:sequence>
				<xs:attribute name="Symbol" type="xs:string" use="optional"/>
				<xs:attribute name="Scale" type="T_Scale" use="required"/>
				<xs:attribute name="Base" type="T_Base" use="required"/>
				<xs:attribute name="Coefficient" type="xs:double" use="required"/>
				<xs:attribute name="Offset" type="xs:double" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="T_Base">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ONE"/>
			<xs:enumeration value="TWO"/>
			<xs:enumeration value="E"/>
			<xs:enumeration value="PI"/>
			<xs:enumeration value="TEN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="T_Datatype">
		<xs:restriction base="xs:string">
			<xs:enumeration value="BOOLEAN"/>
			<xs:enumeration value="INTEGER"/>
			<xs:enumeration value="RATIONAL"/>
			<xs:enumeration value="REAL"/>
			<xs:enumeration value="COMPLEX"/>
			<xs:enumeration value="STRING"/>
			<xs:enumeration value="DATETIME"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="T_Scale">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LINEAR"/>
			<xs:enumeration value="LOGARITHMIC"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="T_URI">
		<xs:restriction base="xs:anyURI">
			<!--<xs:pattern
				value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"
			/>-->
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== anborr/LOIN-XML-Schema/src/xml/Window_DT_Library v3_xlink.xml
<?xml version="1.0" encoding="UTF-8"?>

<DT_Library xmlns="https://iso.org/2022/ProductDataTemplates" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    URI="ba13388f-0253-4595-be2c-66592d4b29eb" 
    xmlns:xlink="http://www.w3.org/1999/xlink" 
    xsi:noNamespaceSchemaLocation="EN_ISO_23387.xsd">
    
  
   
    <LibraryName URI="c951daa2-a6e7-4f03-b01b-779106c6f486" LanguageCode="en">My data template library exchange</LibraryName>
	<LibraryName URI="d951daa2-a6e7-4f03-b01b-779106c6f486" LanguageCode="no-NO">Min datamal-bibliotekutveksling</LibraryName>
	<LibraryName URI="e951daa2-a6e7-4f03-b01b-779106c6f486" LanguageCode="de-DE">Austausch meiner Datenvorlagenbibliothek</LibraryName>
	
    <!-- 
    ############################################################################################################################################
    #  Languages
    #############################################################################################################################################
    -->
	
	<Language URI="09ba94d4-87c0-43d6-aca2-37ab27199883" Code="en" Name="English"/>
	<Language URI="19ba94d4-87c0-43d6-aca2-37ab27199883" Code="no-NO" Name="Norwegian"/>
	<Language URI="29ba94d4-87c0-43d6-aca2-37ab27199883" Code="de-DE" Name="German"/>

    <!-- 
    ############################################################################################################################################
    #  Dimension
    #############################################################################################################################################
    -->

	<Dimension UUID="476c3391-b3a7-4c33-a4e3-2b503726f441" L="1" T="0" M="0" Theta="0" N="0" I="0" J="0"/>

    <!-- 
    ############################################################################################################################################
    #  Unit centimeter
    #############################################################################################################################################
    -->

	<Unit URI="576c3391-b3a7-4c33-a4e3-2b503726f441" Date="2022-05-02T09:21:20+01:00" Symbol="cm" Scale="LINEAR" Base="TEN" Coefficient="100" Offset="0">
		<Name URI="cb66846a-3746-4fe0-bfe9-bc6028180a52" LanguageCode="en">Centimeter</Name>
		<Definition URI="4e5b75bb-78fe-4d85-b32f-f42df5090007" LanguageCode="en">Centimeter according to ISO 80000</Definition>
		<Dimension xlink:title="" xlink:href="476c3391-b3a7-4c33-a4e3-2b503726f441"/>
	</Unit>

    <!-- 
    ############################################################################################################################################
    #  Physical quantity : Length
    #############################################################################################################################################
    -->
    
    <PhysicalQuantity URI="a0b4e8cc-452a-4c47-9043-d90ec5f4bfc3" Date="2022-05-02T09:21:20+01:00">
		<Name URI="01f5560e-8281-4b15-ad10-1b63b90e0649" LanguageCode="en">Length</Name>
		<Definition URI="598ea5b6-0e3d-4316-a394-97c78debdef8" LanguageCode="en">Definition of length physical quantity</Definition>
		<Dimension xlink:title="" xlink:href="476c3391-b3a7-4c33-a4e3-2b503726f441"/>
    </PhysicalQuantity>

    <!-- 
    ############################################################################################################################################
    #  Property : length coming from external dictionary
    #############################################################################################################################################
    -->

	<Property URI="b0b4e8cc-452a-4c47-9043-d90ec5f4bfc3" Date="2022-05-02T09:21:20+01:00">
		<Name URI="db66846a-3746-4fe0-bfe9-bc6028180a52" LanguageCode="en">Length</Name>
		<Definition URI="3e5b75bb-78fe-4d85-b32f-f42df5090007" LanguageCode="en">Lengh according to ISO XXX-YYY</Definition>
		<ExternalDictionary xlink:title="My external dictionary" xlink:href="2bb485a2-928d-4a22-98a7-150b93a7d3f1"/>
		<Datatype>REAL</Datatype>
	</Property>


    <!-- 
    ############################################################################################################################################
    #  Property : Width
    #############################################################################################################################################
    -->

	<Property URI="bc175904-b312-4caa-8b8a-5b130c239673" Date="2022-05-02T09:21:20+01:00">
		<Name URI="db66846b-3746-4fe0-bfe9-bc6028180a52" LanguageCode="en">Width</Name>
		<Definition URI="3b5b75bb-78fe-4d85-b32f-f42df5090007" LanguageCode="en">Width according to ISO XXX-YYY</Definition>
		<Datatype>REAL</Datatype>
		<Unit LinkURI="3e633b70-3f35-453f-844a-dc7ff8555123" xlink:title="cm" xlink:href="576c3391-b3a7-4c33-a4e3-2b503726f441"/>
		<PhysicalQuantity xlink:title="Length" xlink:href="a0b4e8cc-452a-4c47-9043-d90ec5f4bfc3"/>
		<Boundary BoundaryLimit="MIN" Inclusive="false" BoundaryValue="0"/>
	</Property>

    
    <!-- 
    ############################################################################################################################################
    #  Property : Fire classification EN 13501-1+A1
    #############################################################################################################################################
    -->

	<Property URI="e6adff2a-19cb-4b04-8f07-89f3934bbb6c" Date="2022-05-02T09:21:20+01:00">
		<Name  URI="fb66846a-3746-4fe0-bfe9-bc6028180a52" LanguageCode="en">Fire classification</Name>
		<Definition URI="3bc4f4a1-ec3b-46f8-b9f8-5acb4c472486" LanguageCode="en">Fire classification euroclass</Definition>
      	<ReferenceDocument xlink:title="EN 13501-1:2018" xlink:href="aad6923e-94b9-4626-8dc6-a54d537aab4e"/>
		<Datatype>STRING</Datatype>
		<PredefinedValues URI="984178ba-78c5-44a6-a8cb-41543b3ccd3c" LanguageCode="en">
		  <Values>
			<ValueItem OrderNo="1" Value="A1" />
			<ValueItem OrderNo="2" Value="A2" />
			<ValueItem OrderNo="3" Value="B" />
			<ValueItem OrderNo="4" Value="C" />
			<ValueItem OrderNo="5" Value="D" />
			<ValueItem OrderNo="6" Value="E" />
			<ValueItem OrderNo="7" Value="F" />
		  </Values>		
		</PredefinedValues>
	</Property>

    <!-- 
    ############################################################################################################################################
    #  Construction object : Window
    #############################################################################################################################################
    -->
    	
	<ConstructionObject URI="2c9cf451-6070-42dc-bbc8-a71494be6476" Date="2022-05-02T09:21:20+01:00">
			<Name URI="86d4ccdd-cfa1-4e11-821e-56ce6fe1eecf" LanguageCode="en">Window</Name>
			<Definition URI="fc3d13d8-38a0-4385-96fa-e76a92686d78" LanguageCode="en">Definition of a window</Definition>
	</ConstructionObject>
	
    <!-- 
    ############################################################################################################################################
    #  Set of properties  Dimensions
    #############################################################################################################################################
    -->

   <SetOfProperties URI="19f434c3-634d-4fcc-ba62-04106efb8eef" Date="2022-05-02T09:21:20+01:00">
	 <Name URI="4ca1cfed-b6f6-46dc-8fbf-50f4d097c981" LanguageCode="en">Dimensions</Name>
	 <Definition URI="99906938-eb25-439a-ae4e-a4869c63f6fb" LanguageCode="en">Definition of the dimensions set of properties</Definition>
	 <Property xlink:title="Width" xlink:href="bc175904-b312-4caa-8b8a-5b130c239673"></Property>
	 <Property xlink:title="Length" xlink:href="b0b4e8cc-452a-4c47-9043-d90ec5f4bfc3"></Property>	 
   </SetOfProperties>
	


    <!-- 
    ############################################################################################################################################
    #  Data template for Window
    #############################################################################################################################################
    -->

	<DataTemplate URI="2e035990-8bc2-4141-b2ec-8cd0513cdd1f" Date="2022-05-02T09:21:20+01:00">
		<Name URI="5fc19e7b-0108-490b-8140-34462515b2d4" LanguageCode="en">Data Template for Window</Name>
		<Definition URI="da175904-b312-4caa-8b8a-5b130c239673" LanguageCode="en">Definition of the data template</Definition>
		<IsDataTemplateFor LinkURI="3c9cf451-6070-42dc-bbc8-a71494be6476" xlink:title="Window" xlink:href="2c9cf451-6070-42dc-bbc8-a71494be6476"/>
		<SetOfProperties LinkURI="20f434c3-634d-4fcc-ba62-04106efb8eef" xlink:title="Dimensions" xlink:href="19f434c3-634d-4fcc-ba62-04106efb8eef"/>
		<Property xlink:title="Fire classification" xlink:href="e6adff2a-19cb-4b04-8f07-89f3934bbb6c"/>
	</DataTemplate>
	
    <!-- 
    ############################################################################################################################################
    #  Reference Document  EN 13501-1+A1
    #############################################################################################################################################
    -->
    <ReferenceDocument URI="aad6923e-94b9-4626-8dc6-a54d537aab4e" Date="2022-05-02T09:21:20+01:00">
	  <Name URI="cfda6613-35a6-4ace-b657-6320651b5c7c" LanguageCode="en">EN 13501-1:2018 Fire classification of construction products and building elements. Classification using data from reaction to fire tests
	  </Name>
	  <Definition URI="0ec4fed1-f202-4c27-97f0-4421fae7c00a" LanguageCode="en">BS EN 13501-1 provides the reaction to the fire classification procedure for all construction products, including products incorporated within building elements with the exception of power, control and communication cables which are covered by EN 13501-6.</Definition>
    </ReferenceDocument>

    <!--
