=== anborr/LOIN-XML-Schema/src/xml/ISO-23387.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://tempuri.org/XMLSchema.xsd"
		   elementFormDefault="qualified"
		   xmlns="http://tempuri.org/XMLSchema.xsd"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xml:lang="en"
>

	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>

	<xs:annotation>
		<xs:documentation>

		</xs:documentation>
	</xs:annotation>

	<xs:element name="Library">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="Name" type="multilingualTextType" maxOccurs="unbounded" />
				<xs:element name="DataTemplate" type="dataTemplateType" maxOccurs="unbounded" />
				<xs:element name="Property" type="propertyType" maxOccurs="unbounded" />
				<xs:element name="PhysicalQuantity" type="physicalQuantityType" maxOccurs="unbounded" />
				<xs:element name="SetOfProperties" type="groupOfPropertiesType" maxOccurs="unbounded" />
				<xs:element name="Purpose" type="groupOfPropertiesType" maxOccurs="unbounded" />
				<xs:element name="IntendedUse" type="groupOfPropertiesType" maxOccurs="unbounded" />
				<xs:element name="UserDefined" type="groupOfPropertiesType" maxOccurs="unbounded" />
				<xs:element name="ReferenceDocument" type="referenceDocumentType" maxOccurs="unbounded" />
				<xs:element name="Object" type="objectType" maxOccurs="unbounded" />
				<xs:element name="Dimension" type="dimensionType" maxOccurs="unbounded" />
				<xs:element name="Unit" type="unitType" maxOccurs="unbounded" />
			</xs:choice>
			<xs:attribute name="nodeID" type="guidType"/>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="multilingualTextType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute ref="xml:lang" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="unitType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="Symbol" type="multilingualTextType" maxOccurs="unbounded" />
					<xs:element name="Dimension" type="referenceType" />
					<xs:element name="Scale" type="scaleType" />
					<xs:element name="Base" type="baseType" />
					<xs:element name="Coefficient" type="xs:double" />
					<xs:element name="Offset" type="xs:double" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="dataTemplateType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:choice maxOccurs="unbounded">
					<xs:element name="Object" type="referenceType" minOccurs="1" maxOccurs="1" />
					<xs:element name="DataTemplate" type="referenceType" maxOccurs="unbounded" />
					<xs:element name="Property" type="referenceType" minOccurs="1" maxOccurs="unbounded" />
					<xs:element name="SetOfProperties" type="referenceType" minOccurs="1" maxOccurs="unbounded"/>
				</xs:choice>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="dimensionType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="DimensionExponentForAmountOfSubstance" type="xs:int" />
					<xs:element name="DimensionExponentForElectricCurrent" type="xs:int" />
					<xs:element name="DimensionExponentForLength" type="xs:int" />
					<xs:element name="DimensionExponentForLuminousIntensity" type="xs:int" />
					<xs:element name="DimensionExponentForMass" type="xs:int" />
					<xs:element name="DimensionExponentForThermodynamicTemperature" type="xs:int" />
					<xs:element name="DimensionExponentForTime" type="xs:int" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="DataType" type="datatypeType" />
					<xs:element name="Symbol" type="xs:string" minOccurs="0" />
					<xs:element name="Unit" type="referenceType" minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="PhysicalQuantity" type="referenceType" minOccurs="0" />
					<xs:element name="Property" type="referenceType" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="physicalQuantityType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="Dimensions" type="referenceType" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="groupOfPropertiesType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="Property" type="referenceType" minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="SetOfProperties" type="referenceType" minOccurs="0" maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="referenceDocumentType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="DateOfPublication" type="xs:dateTime" minOccurs="0" />
					<xs:element name="Author" type="xs:string" minOccurs="0" />
					<xs:element name="ISBN" type="xs:string" minOccurs="0" />
					<xs:element name="Publisher" type="xs:string" minOccurs="0" />
					<xs:element name="URI" type="xs:string" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="objectType">
		<xs:annotation>
			<xs:documentation>

			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="conceptType">
				<xs:sequence>
					<xs:element name="Object" type="referenceType" minOccurs="0" maxOccurs="unbounded" /> <!--AB: not sure why we need this-->
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="conceptType" abstract="true">
		<xs:sequence>
			<xs:element name="Name" type="multilingualTextType" maxOccurs="unbounded" />
			<xs:element name="Definition" type="multilingualTextType" minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="ReferenceDocument" type="referenceType" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="about" type="xs:anyURI"/>
		<xs:attribute name="nodeID" use="required" type="guidType"/>
		<xs:attribute name="date" type="xs:dateTime" use="required" />
	</xs:complexType>
	<xs:complexType name="referenceType">
		<xs:attribute name="resource" type="xs:anyURI"/>
		<xs:attribute name="nodeID" type="guidType" />
	</xs:complexType>
	<xs:complexType name="datatypeType">
		<xs:sequence>
			<xs:element name="MinInclusive" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						MinInclusive is the inclusive lower bound of the value for a datatype
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="value" type="xs:anySimpleType" />
				</xs:complexType>
			</xs:element>
			<xs:element name="MaxInclusive" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						MaxInclusive is the inclusive upper bound of the value for a datatype
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="value" type="xs:anySimpleType" />
				</xs:complexType>
			</xs:element>
			<xs:element name="MinExclusive" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						MinExclusive is the exclusive lower bound of the value for a datatype
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="value" type="xs:anySimpleType" />
				</xs:complexType>
			</xs:element>
			<xs:element name="MaxExclusive" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						MaxExclusive is the exclusive upper bound of the value for a datatype
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="value" type="xs:anySimpleType" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Pattern" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Pattern is a constraint on the value of a datatype which is achieved by constraining the value to literals which macht a specific pattern.
						The value of pattern must be a regular expression
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="value" type="xs:string" />
				</xs:complexType>
			</xs:element>
			<xs:element name="Enumeration" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Enumeration constrains the value to a specified set of values
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Unit" type="referenceType" minOccurs="0" />
						<xs:element name="Values" type="valuesType" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="BOOLEAN"/>
					<xs:enumeration value="INTEGER"/>
					<xs:enumeration value="RATIONAL"/>
					<xs:enumeration value="REAL"/>
					<xs:enumeration value="COMPLEX"/>
					<xs:enumeration value="STRING"/>
					<xs:enumeration value="DATETIME"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="valuesType">
		<xs:sequence>
			<xs:element name="Value" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:anySimpleType">
							<xs:attribute name="order" type="xs:int" use="optional" />
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute ref="xml:lang" use="optional" />
	</xs:complexType>
	<xs:simpleType name="scaleType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LINEAR"/>
			<xs:enumeration value="LOGARITHMIC"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="baseType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="ONE"/>
			<xs:enumeration value="TWO"/>
			<xs:enumeration value="E"/>
			<xs:enumeration value="PI"/>
			<xs:enumeration value="TEN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="guidType">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				The representation of a GUID, generally the id of an element.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attribute name="nodeID" type="guidType">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Defines the ID of a concept
			</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="resource" type="xs:anyURI">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Defines a resource to identify a concept
			</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="about" type="xs:anyURI">
		<xs:annotation>
			<xs:documentation xml:lang="en">
				Defines the resource being described
			</xs:documentation>
		</xs:annotation>
	</xs:attribute>
</xs:schema>

=== anborr/LOIN-XML-Schema/src/xml/ISO-23387_instance.xml
<?xml version="1.0" encoding="UTF-8"?>
<dt:Library xmlns:dt="http://tempuri.org/XMLSchema.xsd" nodeID="ba13388f-0253-4595-be2c-66592d4b29eb" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tempuri.org/XMLSchema.xsd ISO-23387.xsd">
	<dt:Name xml:lang="en">My data template library exchange</dt:Name>
	<dt:Name xml:lang="no">Min datamal-bibliotekutveksling</dt:Name>
	<dt:Name xml:lang="de">Austausch meiner Datenvorlagenbibliothek</dt:Name>
	<dt:Dimension nodeID="476c3391-b3a7-4c33-a4e3-2b503726f441" date="2022-05-02T09:21:20+01:00" >
		<dt:Name xml:lang="en">Length Dimensions</dt:Name>
		<dt:DimensionExponentForAmountOfSubstance>0</dt:DimensionExponentForAmountOfSubstance>
		<dt:DimensionExponentForElectricCurrent>0</dt:DimensionExponentForElectricCurrent>
		<dt:DimensionExponentForLength>1</dt:DimensionExponentForLength>
		<dt:DimensionExponentForLuminousIntensity>0</dt:DimensionExponentForLuminousIntensity>
		<dt:DimensionExponentForMass>0</dt:DimensionExponentForMass>
		<dt:DimensionExponentForThermodynamicTemperature>0</dt:DimensionExponentForThermodynamicTemperature>
		<dt:DimensionExponentForTime>0</dt:DimensionExponentForTime>
	</dt:Dimension>
	<dt:Unit nodeID="576c3391-b3a7-4c33-a4e3-2b503726f441" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Centimeter</dt:Name>
		<dt:Definition xml:lang="en">Centimeter according to ISO 80000</dt:Definition>
		<dt:Symbol>cm</dt:Symbol>		
		<dt:Dimension nodeID="476c3391-b3a7-4c33-a4e3-2b503726f441"/>
		<dt:Scale>LINEAR</dt:Scale>
		<dt:Base>TEN</dt:Base>
		<dt:Coefficient>100</dt:Coefficient>
		<dt:Offset>0</dt:Offset>
	</dt:Unit>
	<dt:PhysicalQuantity nodeID="a0b4e8cc-452a-4c47-9043-d90ec5f4bfc3" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Length</dt:Name>
		<dt:Definition xml:lang="en">Definition of length physical quantity</dt:Definition>
		<dt:Dimensions nodeID="476c3391-b3a7-4c33-a4e3-2b503726f441"/>
	</dt:PhysicalQuantity>
	<dt:Property nodeID="b0b4e8cc-452a-4c47-9043-d90ec5f4bfc3" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Length</dt:Name>
		<dt:Definition xml:lang="en">Length according to ISO XXX-YYY</dt:Definition>
		<dt:DataType name="REAL"/>
		<dt:Unit nodeID="576c3391-b3a7-4c33-a4e3-2b503726f441"/>
		<dt:PhysicalQuantity nodeID="a0b4e8cc-452a-4c47-9043-d90ec5f4bfc3"/>
	</dt:Property>
    <dt:Property nodeID="75cceb1c-1c7a-44aa-8a75-c3a953e9068b" about="https://datadictionay1.org/75cceb1c-1c7a-44aa-8a75-c3a953e9068b" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Length</dt:Name>
		<dt:Definition xml:lang="en">Length according to ISO XXX-YYY</dt:Definition>
		<dt:DataType name="REAL"/>
		<dt:Unit resource="https://datadictionary2.org/cm" />
		<dt:PhysicalQuantity resource="https://datadictionary3.org/length" />
	</dt:Property>
	<dt:Property nodeID="b0b4e8cc-452a-4c47-9043-d90ec5f4bfc3" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Width</dt:Name>
		<dt:Definition xml:lang="en">Width according to ISO XXX-YYY</dt:Definition>
		<dt:DataType name="REAL">
			<dt:MinExclusive value="0"/>
		</dt:DataType>
		<dt:Unit nodeID="576c3391-b3a7-4c33-a4e3-2b503726f441"/>
		<dt:PhysicalQuantity nodeID="a0b4e8cc-452a-4c47-9043-d90ec5f4bfc3"/>
	</dt:Property>
	<dt:Property nodeID="e6adff2a-19cb-4b04-8f07-89f3934bbb6c" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Fire classification</dt:Name>
		<dt:Definition xml:lang="en">Fire classification euroclass</dt:Definition>
		<dt:ReferenceDocument nodeID="aad6923e-94b9-4626-8dc6-a54d537aab4e"/>
		<dt:DataType name="STRING">
			<dt:Enumeration>
				<dt:Values xml:lang="en">
					<dt:Value order="1">A1</dt:Value>
					<dt:Value order="2">A2</dt:Value>
					<dt:Value order="3">B</dt:Value>
					<dt:Value order="4">C</dt:Value>
					<dt:Value order="5">D</dt:Value>
					<dt:Value order="6">E</dt:Value>
					<dt:Value order="7">F</dt:Value>
				</dt:Values>
			</dt:Enumeration>
		</dt:DataType>
	</dt:Property>
	<dt:Object nodeID="2c9cf451-6070-42dc-bbc8-a71494be6476" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Window</dt:Name>
		<dt:Definition xml:lang="en">Definition of a window</dt:Definition>
	</dt:Object>
	<dt:SetOfProperties nodeID="19f434c3-634d-4fcc-ba62-04106efb8eef" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Dimensions</dt:Name>
		<dt:Definition xml:lang="en">Definition of the dimensions set of properties</dt:Definition>
		<dt:Property nodeID="bc175904-b312-4caa-8b8a-5b130c239673"/>
		<dt:Property nodeID="b0b4e8cc-452a-4c47-9043-d90ec5f4bfc3"/>
	</dt:SetOfProperties>
	<dt:DataTemplate nodeID="2e035990-8bc2-4141-b2ec-8cd0513cdd1f" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">Data Template for Window</dt:Name>
		<dt:Definition xml:lang="en">Definition of the data template</dt:Definition>
		<dt:Object nodeID="2c9cf451-6070-42dc-bbc8-a71494be6476"/>
		<dt:SetOfProperties nodeID="19f434c3-634d-4fcc-ba62-04106efb8eef"/>
		<dt:Property nodeID="e6adff2a-19cb-4b04-8f07-89f3934bbb6c"/>
	</dt:DataTemplate>
	<dt:ReferenceDocument nodeID="aad6923e-94b9-4626-8dc6-a54d537aab4e" date="2022-05-02T09:21:20+01:00">
		<dt:Name xml:lang="en">EN 13501-1:2018 Fire classification of construction products and building elements. Classification using data from reaction to fire tests</dt:Name>
		<dt:Definition xml:lang="en">EN 13501-1 provides the reaction to the fire classification procedure for all construction products, including products incorporated within building elements with the exception of power, control and communication cables which are covered by EN 13501-6.</dt:Definition>
	</dt:ReferenceDocument>
</dt:Library>
